### ISSUE TITLE
Should Property.lazyLink be called Property.addListener?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#114]
From https://github.com/phetsims/axon/issues/70

Should Property.lazyLink (the one that doesn't get an automatic callback with the current value) be called Property.addListener?

**Comment by pixelzoom** [comment]
Imo, no.

**Comment by samreid** [comment]
I don't feel strongly one way or the other about this, perhaps a quick chat in developer meeting would be enough to help us decide.

**Comment by pixelzoom** [comment]
To clarify... I prefer `link` and `lazyLink` because these names communicate both their similarity and difference. That is, they both register an observer in exactly the same way, and the latter defers calling the observer until the value changes.  Having different names for these functions (`link` and `addListener`) obscures both their similarity and difference.

**Comment by samreid** [comment]
That argument is good enough for me!  Closing.
