### ISSUE TITLE
inconsistent use of options.tandem in Property.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#122]
Property.js:

```js
99  options.tandem.supplied && options.tandem.addInstance( this, TProperty( options.phetioValueType, {
...
121  options.tandem && options.tandem.removeInstance( self );
```

Line 99 assumes that options.tandem exists. 
Line 121 assumes that options.tandem may not exist.
Which is correct?

**Comment by samreid** [comment]
@zepumph I think we can addInstance even on unsupplied tandems, right?  So I'm not sure that check is necessary.  Can you take a look?

**Comment by zepumph** [comment]
I think that this is placed here defensively not for addInstance, which can handle `!tandem.required && !tandem.supplied` but the TProperty parametric call expects a truthy when FunctionWrapper surrounds the link function. This comes back to the conversation about phet vs phet-io in how loudly we fail. Maybe it would be best for us to guard against this in TProperty or TFunctionWrapper instead of adding a check to addInstance, which inherently seems worse, but maybe that would silence other errors in the future.

**Comment by zepumph** [comment]
@samreid the above paragraph is exhaustive, basically I am trying to figure how to handle the fact that in TProperty, the inherit call call's TFunctionWrapper(), which will throw an error if there is no phetioValueType passed in. It seems like the best way to handle this right now, is to just check before adding the instance.

`options.tandem.supplied && . . .` seems like a better option that needing any kind of reference to the tandem in the TType.

**Comment by samreid** [comment]
Assigned for discussion on the next PhET-iO day.

**Comment by zepumph** [comment]
We removed tandem.supplied, and are instead using this line to make sure there is always an argument for TProperty. 

```js
    // Register with tandem. TVoid is needed when not running in phet-io mode, and the phetioValueType wasn't supplied.
    options.tandem.addInstance( this, TProperty( options.phetioValueType || TVoid, {
      phetioInstanceDocumentation: options.phetioInstanceDocumentation,
      phetioStateElement: options.phetioStateElement
    } ) );

**Comment by zepumph** [comment]
I made the commit above. Things are much more streamlined and consistent now. Thanks all, closing
