### ISSUE TITLE
How should axon Property types be annotated?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#125]
Some examples from Function Builder:

```js
    // Full type documented
    // @public {Property.<Scene>} the selected scene
    this.selectedSceneProperty = new Property( options.defaultScene );

    // Only document the inner type
    // @public (read-only) {Vector2} DO NOT set this directly! Use moveTo or animateTo.
    this.locationProperty = new Property( options.location );

    // No type documentation, even when it would be useful
    // @public
    this.fillProperty = new Property( options.fill );

    // full type to the side
    // @public
    this.operandProperty = new Property( options.operand ); // {Property.<number>}

    // no type specified because a constant is supplied
    // @private number of rows in the table
    this.numberOfRowsProperty = new Property( 0 );
```

**Comment by samreid** [comment]
I'm a fan of the top one when the type is not obvious, and the bottom one when the type is obvious.

**Comment by jonathanolson** [comment]
I've lately typically done the full documentation unless it is a directly copied constructor argument (in which case I provide visibility). I've noticed that I personally find it more helpful to read when fully documented, as it's easy to scan to determine the type.

For my recent sim code, documentation for something like the `fillProperty` above is simpler, since it's always a `Property.<Color>` from the color profile.

**Comment by pixelzoom** [comment]
Should be fully documented, e.g.:

```js
    // @public {Property.<Scene>} the selected scene
    this.selectedSceneProperty = new Property( options.defaultScene );
```

The other examples are incompletely documented, which should have been noted during code review.

**Comment by pixelzoom** [comment]
I corrected function-builder type expressions for Property and DerivedProperty in the above commit.  Back to @samreid.

**Comment by samreid** [comment]
7e385deaadde056ed3c7832de80a30fa92645ba0 looks excellent, thanks!  Closing.
