### ISSUE TITLE
Don't allocate listener array before sending notifications

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#13]
As discussed in a recent developer meeting, we could skip allocation of the listener array when sending Property.js notifications.  It seems the fastest way would be to maintain two lists and sync after the set method if one changed.  
Flag 1. Are you in an iteration over observers flag (true in slice and false after the loop).
Flag 2. Was the observer list modified during the loop traversal
Centralize push/remove listeners, so it can maintain two lists.

Flag must be a counter, if it needs to be re-entrant.

Another way to avoid the allocation (but slower) would be to use listenerCopy.length=0 and push all.

**Comment by pixelzoom** [comment]
@jonathanolson what is left to do on this issue?

**Comment by jonathanolson** [comment]
I'm satisfied with onStatic/offStatic. I believe the above stated case may be impossible to do (as noted elswhere) since we wouldn't just need two lists, it could be many more (with the below devious case).

In particular, for event E if you had N normal listeners, and then a final listener with 2 steps when called: "Remove a normal listener, or if none, remove this listener", and "trigger event E again", then you essentially need N listener lists to do this properly (where the 1st listener is called only once, 2nd listener called twice, Nth listener called N times, etc.).

I'd recommend closing this issue, and if we run into Property-specific performance problems, using onStatic/offStatic. If those aren't sufficient, we can look into something like this again, that would fall back to slice() when it needs to (e.g. for the above breaking case).

**Comment by jonathanolson** [comment]
Didn't see any objections, closing for now.
