### ISSUE TITLE
Instrument NumberProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#136]
From https://github.com/phetsims/beers-law-lab/issues/206#issuecomment-325746591

@pixelzoom tried to use the 'range' option of NumberProperty to fix a problem in Instance Proxies. Currently the only fix is to explicitly give TNumber the range. It would be nice if we handled that in NumberProperty. If there is a range, then automatically add that to the `TNumber()` parametric call. Tagging @samreid for suggestion

**Comment by pixelzoom** [comment]
@zepumph This involves more than NumberProperty.  I created the general issue in phet-io (https://github.com/phetsims/phet-io/issues/1210), but then realized that it should be in axon, so moved it to  https://github.com/phetsims/axon/issues/137.   So... I'm closing this issue, since it's a subset of    https://github.com/phetsims/axon/issues/137.
