### ISSUE TITLE
Review DynamicProperty

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/axon#152]
Can you review AXON/DynamicProperty? I believe it's ready for general usage.

**Comment by jbphet** [comment]
I spent a little time looking at this, and I have some preliminary thoughts and questions.  When this was first described to the group during a dev meeting, I understood the basic idea to be a property the essentially "wrapped" another so that the resultant property could have its underlying property swapped.  This would allow other code to stay linked to the resultant property.  I believe I said that I've run into cases where this would have been useful.  The current version of DynamicProperty does this, but it seems to me that it puts a lot of the onus on the client to manage it, since it requires the management of an external property that contains the property values.  I had assumed that this would be done by DynamicProperty, and before going further I'd like to understand why this *wasn't* done.  To elaborate, here is the example from the header in `DynamicProperty.js`

```js
var firstProperty = new Property( Color.RED );
var secondProperty = new Property( Color.BLUE );
var currentProperty = new Property( firstProperty ); // {Property.<Property.<Color>>}

var backgroundFill = new DynamicProperty( currentProperty ) // Turns into a {Property.<Color>}
backgroundFill.value; // Color.RED, since: currentProperty.value === firstProperty and firstProperty.value === Color.RED
firstProperty.value = Color.YELLOW;
backgroundFill.value; // Color.YELLOW - It's connected to firstProperty right now

currentProperty.value = secondProperty;
backgroundFill.value; // Color.BLUE - It's the secondProperty's value

secondProperty.value = Color.MAGENTA;
backgroundFill.value; // Color.MAGENTA - Yes, it's listening to the other Property now.
```

In this example, `currentProperty` has to be maintained externally by the client code, which seems like a hassle.  Why not have `DynamicProperty` encompass `currentProperty`, and have a method for setting a new property?

Another question is about the type spec for the constructor.  It currently says, `{Property.<*|null>} valuePropertyProperty`, but I believe (from the example above, among other places) that it is a property that contains a property, so shouldn't it be `{Property<Property.<*|null>>} valuePropertyProperty`?

I haven't looked at the `map` and `derived` options yet.  I'll do so once we have some of the preliminary questions worked out.

**Comment by jonathanolson** [comment]
> Another question is about the type spec for the constructor. It currently says, {Property.<*|null>} valuePropertyProperty, but I believe (from the example above, among other places) that it is a property that contains a property, so shouldn't it be {Property<Property.<*|null>>} valuePropertyProperty?

Nope, see the `derive` option. It is of type `{Property.<Scene>}` in the example for `derive`.

> Why not have DynamicProperty encompass currentProperty, and have a method for setting a new property?

I guess I designed it this way because I honestly haven't yet run into a case where I didn't already have a Property of the object. I definitely wouldn't want to have to create a dynamic property AND every time have a link afterwards.

That said, doesn't `new DynamicProperty( new Property( null ) )` (and you set `dynamicProperty.valuePropertyProperty`'s value, if it is made public or do some equivalent) work?

**Comment by samreid** [comment]
Can you please add a code comment that elaborates on why this callback only does something if the value is externally changing?  What would go wrong if we omitted the if statement?

```js
    function linkProperty( property, propertyProperty ) {
      property.link( function( value ) {
        if ( property.isExternallyChanging ) {
          editedCallback();
          makeNotDirty();
          propertyProperty.value.highlightProperty.value = Highlight.NORMAL;
        }
      } );
    }
```

**Comment by samreid** [comment]
What does this comment mean?
```js
* TODO: DerivedProperty should only need to do this, not all of the other methods it's also doing
```

**Comment by samreid** [comment]
This listener is added in the constructor:

```js
    // If we aren't bidirectional, we should never add this listener.
    if ( options.bidirectional ) {
      this.lazyLink( this.onSelfChange.bind( this ) );
    }
```
Perhaps comment that it is does not need to be `unlinked` in the dispose because all self listeners are removed in Property.dispose?

**Comment by samreid** [comment]
In https://github.com/phetsims/axon/issues/39 we decided to remove higher-order "convenience" functions on Property.  Not all of the arguments made in that issue apply to DerivedProperty, but it feels like it is of the same ilk.  I recommend scheduling at least 30 minutes for @pixelzoom to read the API docs of DerivedProperty and make a recommendation.  @ariel-phet can @pixelzoom spare the time in the coming month or so?

**Comment by jonathanolson** [comment]
> In #39 we decided to remove higher-order "convenience" functions on Property.

Can you point to something like a convenience function/feature here that, if removed, wouldn't significantly increase the code size of client call sites?

**Comment by jonathanolson** [comment]
> Can you please add a code comment that elaborates on why this callback only does something if the value is externally changing? What would go wrong if we omitted the if statement?
> Perhaps comment that it is does not need to be unlinked in the dispose because all self listeners are removed in Property.dispose?

Added comments in the code.

> What does this comment mean?

Looks like DerivedProperty changed since I made that, removed it.

**Comment by samreid** [comment]
@jonathanolson did you address this request?

> Can you please add a code comment that elaborates on why this callback only does something if the value is externally changing? What would go wrong if we omitted the if statement?

**Comment by jonathanolson** [comment]
> @jonathanolson did you address this request?

Yes, I believe https://github.com/phetsims/area-model-common/commit/fdebdce5b38902eea9a429177a599cc33bef401b did? Let me know if it is insufficient.

**Comment by samreid** [comment]
Looks good, thanks. Unassigning self and leaving assigned to @ariel-phet regarding https://github.com/phetsims/axon/issues/152#issuecomment-381675275

**Comment by pixelzoom** [comment]
Self assigning by request from @ariel-phet, "30 minutes of your time in the next month or so".

**Comment by pixelzoom** [comment]
Overall code and (especially) documentation look great.

Recommendations:

- [ ] In constructor, `assert && assert( valuePropertyProperty instanceof Property, … );`  If you provide a non-Property, it currently fails later in the code.

- [ ] The current units tests lack any tests that verify robust handling of illegal actions. The current unit tests  For example, attempting to directly set the value of a non-bidirectional DynamicProperty. Add unit tests for illegal actions.

- [ ] Fix documentation for `set`. It currently says `Prevent setting this Property manually`, but you can in fact call `set` if `bidirectional`.

Back to @jonathanolson.

**Comment by jonathanolson** [comment]
I believe I handled the above issues with the above commit, can you verify (and close?)
