### ISSUE TITLE
Rename Emitter's `argumentTypes`

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#212]
from #182 
Since creating `Validator` this name is not really accurate. Instead @samreid @chrisklus and @zepumph were thinking that it could be `argumentValidators` or `argumentValidatorOptions`.

both of those are pretty lengthy, and we don't love the idea of writing those for every emitter in the future. Also ValidatorOptions is more of the proper type that Validator, since it is an array of the options, not type `{Validator}`

Maybe `argValidatorOptions` isn't too verbose?

**Comment by samreid** [comment]
Since this will be prevalent in client code, we may want to optimize it even further.  Perhaps something like `validators`.  We could rename `Validator` to `Validation` if necessary.

**Comment by zepumph** [comment]
Feel free to edit inline

Naming options for validating:
`Validator.validate` // the way it is now
`Validation.validate`

Names for Emitter option:

`argumentTypes`
`argumentValidation`
`validation`
`validators`
`validationOptions`

**Comment by chrisklus** [comment]
I just experienced this confusion firsthand (despite being a part of this issue only six days ago, how sad!) and think that if arguments is part of the name, then it shouldn't be used as a descriptor for another noun, since this array include the actual arguments as well.

Of the options listed so far, I think I prefer just `validators` the most. Because the documentation will explain that a validator includes the value as part of it, while something like `argumentValidators` or `argValidatorOptions` gives me the initial thought that the array is only validation *for* the arguments.

**Comment by zepumph** [comment]
Marking for a quick dev meeting issues. What should the option name be for the list of validator options objects that are used to validate each arg. Some examples are above. Here are my favorites.

`argValidators`
`argumentValidators`
`validators`

**Comment by samreid** [comment]
`validators` seems best to me.

**Comment by jessegreenberg** [comment]
@pixelzoom said this is a list of options, so how about `validatorOptions`?

Consensus: if we call them `validators`, then rename Validator to something else.

**Comment by pixelzoom** [comment]
More 2/7/19 dev meeting notes:

There was more discussion, but we didn't reach a final decision on this.  

One proposal was to move `Validator.validate` to validate.js and `Validator.validateOptions` to validateOptions.js or isValidator.js.  In both cases, rename `options` params to `validator`.  But what to do about `DEFAULT_OPTIONS`?

@zepumph Pointed out that isValidator.js would be doing something similar to PaintDef.js, but using a totally different approach. Why?

**Comment by zepumph** [comment]
Work done:

* separate out `validate` function to its own file
* rename Validator.js -> ValidatorDef.js
* rename Emitter option `argumentTypes` -> `validators`

@pixelzoom will you please review.

**Comment by pixelzoom** [comment]
Looks good.  I made 4 commits above, 3 of which are cosmetic.  But there was one bug, fixed in https://github.com/phetsims/axon/commit/89500ae5af4d28472581a9e9ec74e93a668815c8 - `Array` needs to be handled before other types because `Array` has a constructor. 

Back to @zepumph in case there's anything else to do.

**Comment by pixelzoom** [comment]
The answer to this TODO in ValidatorDef.js is probably "not right now". 

```js
47 // TODO: do we need a isValidatorDef function? See https://github.com/phetsims/axon/issues/212
```

**Comment by zepumph** [comment]
Thank you so kindly for the quick review! You are right, probably so. I'm going to remove that todo, but, especially as part of work done in https://github.com/phetsims/axon/issues/204, I think that we will need a predicate soon (something to return a boolean instead of assertions.
