### ISSUE TITLE
change options pattern in type-specific Properties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#234]
Related to https://github.com/phetsims/dot/issues/88#issuecomment-470692197 and discussed in https://github.com/phetsims/phet-info/issues/96, @samreid and @zepumph convinced me that the options pattern currently used in type-specific Properties has a potential problem -- it modifies the options value that it was passed.  And we should not do that, in the case the value is used elsewhere. 

I'll self-assigning to change `BooleanProperty`, `NumberProperty` and `StringProperty` (and possibly `Vector2Property`).   And I'll verify that unit tests are up to snuff.  If someone else would like to do this, before I get to it, feel free to reassign.

**Comment by pixelzoom** [comment]
@samreid @zepumph thanks for the options discussion yesterday.  I learned some things, test drove the "best practices" in gas-properties (they are an improvement), and I'm onboard with this change.

**Comment by pixelzoom** [comment]
Looks like we need to resolve https://github.com/phetsims/axon/issues/235 and https://github.com/phetsims/axon/issues/236 before proceeding with this issue.

**Comment by pixelzoom** [comment]
I went ahead and did this, since since it should make whatever we decide in #235 and #236 easier to apply. 

I tried to follow our decisions in https://github.com/phetsims/phet-info/issues/96, and apply the best practices consistently to all 4 subclasses.  

To avoid the ugly/repetitive `!options` expression in `assert( !options || !options.hasProperty( 'blah' ), ...)`, I put such assertions inside an `if ( options )` statement. 

I structured the `_.extend` calls to produce the fewest number of objects.   So to fill in superclass options that are controlled by the subclass, I did `_.extend( {...}, options )`, not `_.extend( {}, options, {...} )`.  Since we've already asserted that the superclass options are not in `options`, these are guarantee to be equivalent, with the latter requiring 1 less object literal.

@samreid or @zepumph would one of you please review?

**Comment by zepumph** [comment]
This is all looking nice. It still looks weird to me to have the double extend call, but I think overall this is looking really nice. 

I know I have brought this up in a similar issue, but I don't love that the `if( options )` block is a duplicate in `BooleanProperty` and `EnumerationProperty`. I don't see an obvious way to factor this out though, especially since many Property subtypes specify exactly what validating options that they allow, (like StringProperty and NumberProperty). I don't recommend any changes here, but if you think of anything I'd be interested in hearing! Back to you.
