### ISSUE TITLE
Rename Action, instances of {Action}, and Action.emit()

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#243]
From #222 and its review, we need a few renames. @pixelzoom wrote:

>@zepumph said:
>> * Rename Action.js
>
>+1 if you come up with a better name. `PhetioAction?`
>
>> * Rename `Action.emit()` and perhaps separate that from `Emitter.emit()`.
>
>+1.   Something like "perform" or "do" seems more appropriate. 
>
>> * Rename `Action` instances that are named like `this.mouseUpEmitter = new Action(. . .;`
>
>+1. Defer until `Action` name stabilizes.

I think that a `Phetio` prefix may be superfluous, but I'm open to suggestions. This will effect the public phet-io api, marking as blocks publication. @samreid @chrisklus what do you think they should be named. Should we bring it to dev meeting?

**Comment by samreid** [comment]
Action is described as:

>  An action that can be executed and sent to the PhET-iO data stream, and optionally recorded for playback. This type will also validate the argument types passed to the action function.

I think it would be redundant and inconsistent to name as `PhetioAction`.  After all, `Property` and `Circle` are fully instrumented for PhET-iO, but we do not call them `PhetioProperty` and `PhetioCircle`.

**Comment by zepumph** [comment]
At developer meeting we decided on `Action` and, as a method, `execute`.

**Comment by zepumph** [comment]
- [ ] I should make sure to cover handlePlaybackEvent too.

**Comment by zepumph** [comment]
Promoting to a comment after the commits:

- [x] I should make sure to cover handlePlaybackEvent too.
- [ ] ActionIO still uses the event name "emitted". It would be nice if that was different for Actions and Emitters.
- [ ] I should make an issue in the sonification repo to update those usages as needed.
- [ ] Do we want `ActionIO.execute` to be a public method? Maybe we only need to add it when we need to.
- [ ] Note about baseline update since I changed a lot here. It is annoying that the file is cached, such that when I run grunt update for all baseline files, I need to still have the dev tools open while fuzzing to make sure the old cached baseline isn't loaded. I just want @samreid and @chrisklus to read this. No action necessarily.

**Comment by samreid** [comment]
The renaming as requested in this issue has been implemented nicely, nice work!  Some comments:

I'll bring it up here, but it may warrant a separate issue: Because Emitter extends Action, the following is now possible:

```js
const myEmitter = new Emitter();
myEmitter.execute();
```

Is that acceptable?  If not, how should we get around it?  One way would be to have Emitter extend PhetioObject and compose Action and TinyEmitter instead of extending Action.  May be good to discuss with @pixelzoom.

> ActionIO still uses the event name "emitted". It would be nice if that was different for Actions and Emitters.

Perhaps rename that event to "executed".  I believe all events recorded for playback are done via Action and we do not plan to play back Emitter events.  If this is correct, perhaps it should be documented in Emitter doc and handlePlaybackEvent comments. 

> Do we want ActionIO.execute to be a public method? Maybe we only need to add it when we need to.

Let's not add it at the moment.  It seems like Action is designed to be internal functionality.  If we see a need for a client to execute one of them (like resizedEmitter.execute), perhaps that should be done with a separate API call (like simIO.setSize(width,height)).

> Note about baseline update since I changed a lot here. It is annoying that the file is cached, such that when I run grunt update for all baseline files

Do you think we should add something like ?cacheBuster for it?  Could be done in a separate issue.

> https://github.com/phetsims/balloons-and-static-electricity/commit/c44fd7a5a1a88522575ffcb6735f5b0b8f70cacc

Some Actions are named past tense and some are present tense.  Should we be consistent about this?  If so, which tense is preferable?  This could be a new issue.

ActionIO has stale documentation that refers to Emitter and emit.

**Comment by zepumph** [comment]
>Is that acceptable? If not, how should we get around it? One way would be to have Emitter extend PhetioObject and compose Action and TinyEmitter instead of extending Action. May be good to discuss with @pixelzoom.


@samreid and I were thinking one way to proceed would be to have emitters emit, and actions execute. And so we propose the following steps:
   * Override the execute function in Emitter.js to throw an assertion:
```
    emit() {
      super.execute.apply( this, arguments );
    }

    execute() {
      assert && assert( false, 'Emitter should use "emit" instead of "execute."' );
    }
```
  
  * Create an Action option to specify the name of the event being put on the data stream, defaulting to "executed." Then in Emitter.js we can add `options.phetioEventName = 'emitted';` to pass up to Action.

@pixelzoom we are a bit on the fence about doing the above strategy, or using composition to have an Action in Emitter. We like the idea of making Action.js an implementation detail of Emitter, and don't like having pieces of it leaking out (like being able to call execute on Emitter instances). Perhaps the steps above are enough to keep Action from "leaking" into Emitter, but if not we should think through other steps to hide that implementation detail.


>Do we want ActionIO.execute to be a public method? 

Depending on how a conversation goes above with @pixelzoom, we think that EmitterIO shouldn't extend ActionIO. That will likely simplify how EmitterIO is set up. No part of EmitterIO really needs pulic info from ActionIO. There is some parsing logic in ActionIO to get validators and what not. It may be worth exploring. 

>Do you think we should add something like ?cacheBuster for it? Could be done in a separate issue.

see https://github.com/phetsims/chipper/issues/755

>Some Actions are named past tense and some are present tense. Should we be consistent about this? If so, which tense is preferable? This could be a new issue.

see https://github.com/phetsims/phet-io/issues/1463

- [ ] ActionIO has stale documentation that refers to Emitter and emit.

@pixelzoom is there a time that we could discuss the first point here?

**Comment by pixelzoom** [comment]
> @pixelzoom we are a bit on the fence about doing the above strategy, or using composition to have an Action in Emitter. ...  @pixelzoom is there a time that we could discuss the first point here?

In light of the problems that have been described, it seems like composition is likely more appropriate here and should be investigated.   Happy to discuss whenever I'm on Slack, or set up a time if that doesn't work.

> Depending on how a conversation goes above with @pixelzoom, we think that EmitterIO shouldn't extend ActionIO.  ...

Agreed, if Emitter uses Action via composition.  But if `Emitter extends Action`, then I'd expect `EmitterIO extends ActionIO`.  I.e., I'd expect to see the same pattern for the class and IO type.

**Comment by zepumph** [comment]
Discussed yesterday during phet-io team meeting. The next step is to take the "composition" approach for a test drive. I would like to have @samreid along when exploring this.

**Comment by zepumph** [comment]
Discussed in dev meeting today, @pixelzoom wants to publish ph-scale before too long. We decided this doesn't need to block publication currently, but once we do the work to convert from inheritance to composition it should block publication until things get sorted out.

We will let @pixelzoom know when we want to work on this, and perhaps hold off on this until he has taken rc shas.

**Comment by pixelzoom** [comment]
@zepumph said:
> ... We will let @pixelzoom know when we want to work on this, and perhaps hold off on this until he has taken rc shas

I have published 1.3.0-rc.1 for ph-scale and ph-scale-basics, so all clear to proceed.

**Comment by samreid** [comment]
After spending a few minutes on this, it's unclear to me whether composition will be an improvement.  For instance, `Emitter extends PhetioObject and contains Action` leads to complication with respect to the options.  Which phet-io options do we send to the supertype and which do we send to the Action?  Will we need to support both?  Why make this API more complicated by splitting out Action options from Emitter options?   Maybe we should rationalize this by saying that when you `execute` an `Emitter` that is synonymous with emitting.

For the sake of argument, say we have a `Mammal` type which has method `speak`.  `Cat` overrides `speak` to have `console.log('meow')`, and we decide to also add `Cat.meow()`, which calls `this.speak()`.  What's the problem here?  Having two ways to do the same thing?

Running this past @zepumph as a first line of defense before asking @pixelzoom.

**Comment by zepumph** [comment]
I think I agree with most of the above sentiment. I also think that emitters should not expose execute as a function. Here having two ways to do the same thing is a maintainability concern, for example right now an emitter executing and emitting may be the same thing, but not always in the future. Also it will be harder to update actions if some execute methods pertain to a sub type. 

I propose manually cutting out action related API in emitter that we deem implementation details. This will probably just look like an override with an error. 


A note about your composition attempt. It was my understanding that when making this change, emitter would not extend PhetioObject, and so any phetio related options would either become nested (less ideal), or be passed to the action, and the action would be the only instrumented piece. That is also less than ideal because we would then probably want to support emitter instances calling phetio object methods. 

So far I like keeping Inheritance most.

**Comment by samreid** [comment]
@pixelzoom can you review the preceding comments and recommend a course of action?

**Comment by pixelzoom** [comment]
> They cannot have the same phetioID and we do not want all emitters to show in the data stream like `simulation.screen1.model.ageChangedEmitter.action` executed.

Why not? That seems both correct and accurate.

**Comment by samreid** [comment]
That seems to be leaking an implementation detail.  Why should clients need to know or care to know what `Emitters` contains `Actions`?

**Comment by pixelzoom** [comment]
If we weren't concerned with PhET-iO, I doubt that we'd be having this discussion about inheritance vs composition.  Composition is the clear choice here, and we seemed to agree on that awhile back in the comments.   But now we're rationalizing ("Maybe we should rationalize this by saying...") that inheritance is the way to go.  I don't think PhET-iO should weigh so heavily on our decisions about whether to use inheritance or composition, and I'm afraid that this may indicate a design flaw.

**Comment by samreid** [comment]
> Composition is the clear choice here, and we seemed to agree on that awhile back in the comments

I'd love to hear a response to the `Mammal` argument in https://github.com/phetsims/axon/issues/243#issuecomment-495827010.

**Comment by pixelzoom** [comment]
If I understand the `Mammal` argument...  

You're saying that `meow` calls `speak` and adds no new functionality, therefore having a `Cat` either `meow`  or `speak` is correct.  I.e.

`meow() { this.speak(); }`

And the analogy applies to `Emitter` because `emit` calls `execute` and adds no new functionality. And that is currently true:

```js
emit() {
  this.execute.apply( this, arguments );
}
```

Problems with this analogy...

First, it has maintenance consequences.  It's impossible to enforce that `meow` is equivalent (and remains equivalent) to `speak`.  Ditto for `emit` and `execute`.  

Second, it's bad design.  Adding aliases for `speak` like `Cat.meow`, `Dog.bark`, etc. would be a misguided attempt at realism. It doesn't improve the implementation and has negative maintenance consequences.  If you allow `meow` and `speak` to be used interchangeably, you've accomplished nothing other than creating a future problem. 

Finally, the analogy doesn't hold up when we look at the class hierarchies.  Yes, a Cat is a Mammal, so `Cat extends Mammal` is without a doubt correct.   Ditto for `Dog extends Mammal`.  And `Cat` and `Dog` make sense as sibling subclasses.   Now let's look at `Emitter` and `Action`.    And `Emitter` is not clearly a type of `Action`.  `Action` provides PhET-iO functionality.  `Emitter` is not a way to specialize the role of `Action`, it's a way to notify listeners using `Action` to record that notification in the data stream.   And if I have `Emitter extends Action` and `SomethingElse extends Action`,  you will have a difficult time convincing me that `Emitter` and `SomethingElse` makes sense as sibling classes.

**Comment by zepumph** [comment]
Here is the way I think we should proceed:
* Have `Emitter` extend `Action`, with everything implemented as is for the most part
* Create a stub function `Emitter.execute` to make sure that Emitter instances don't bypass the Emitter.emit api. `Emitter.execute` will throw an error when called.

Rationale:
* `Emitter.emit` is a prolific api across the project. It is nice and people are used to it, there is no reason to change that. The implementation of `Emitter.emit()` currently calls over to `Action` for the majority of its functionality, but there is no reason to leak that into the public api.
* By keeping inheritance, we save big on the phet-io front. If we used composition, then all phet-io options would need to be passed to Action, and the Emitter wouldn't actually be instrumented. This means we would either need to create forwarding methods, or do something like `Emitter.action.tandem.supplied` or `Emitter.action.isPhetioInstrumented`. This is a deal breaker to me. One of the main reasons to split these two up is to make more modular code and responsibility for instrumented Emitters. This tradeoff is balance off of the only con I have heard so far: that it exposes Action methods that we don't want to be exposed. `execute` is the only public method, seems much simpler to manage that. We also haven't mentioned that `Action.validators` makes sense to have directly on Emitter. This was rambley, here is a summary: While it may seem like using composition is "hiding implementation detail," I argue that in fact inheritance is a better way to hide the implementation detail.

**Comment by samreid** [comment]
It seems we should have a discussion on this, marking for dev meeting.

**Comment by pixelzoom** [comment]
As a counter analogy... `Rectangle extends Node` seems natural.  `Node extends Events` seems is questionable and has been discussed more than once.  `Emitter extends Action` seems more similar to the latter than the former.

**Comment by zepumph** [comment]
Developer meeting consensus from today (from SR):

We will keep it the way it is because it is cheap and easy, adding the override to `Emitter.execute` to error out when called. If this in inadequate in the future we can investigate the refactor to use composition more thoroughly.

**Comment by zepumph** [comment]
Comitted above. @samreid please review.

**Comment by samreid** [comment]
This seems to be a reasonable compromise, the change set looks good.  Closing.
