### ISSUE TITLE
Should all listeners present at start of event always be called?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/axon#249]
PhET made a design decision that all listeners (and only listeners) present at the start of an event are called. From https://github.com/phetsims/axon/issues/72#issuecomment-147158108

> Let's say I have listener A and listener B. Listener A removes listener B.
> Then when I emit(), should listener B get a callback?

The decision was "Yes". And this seems to be a convention for other frameworks too. But I encountered a case while using `timer` where this was undesirable (https://github.com/phetsims/axon/issues/248) and ended up adding a `hasListener` check before calling and removing a listener in `timer.setTimeout` because the delayed listener may have already been removed by another listener during `emit`.

I read through https://github.com/phetsims/axon/issues/72 but couldn't find why PhET made this decision. Does anyone know? Are there other cases where it is not desirable to call all listeners present at the start of an event? In the "A and B" listener example above, is it generally just the responsibility of listener A to check that listener B is still attached?

**Comment by samreid** [comment]
In https://github.com/phetsims/axon/issues/248#issuecomment-492760558 @jonathanolson said:

> DOM events and other event systems I've worked with do typically have the convention that the array of listeners at the point of the event are the ones that will be notified. I recall some more practical examples of how it's beneficial (and avoids infinite loops if you remove and re-add a listener in a callback), but I'd have to think more on it.

**Comment by pixelzoom** [comment]
+1 for "Yes".  Notification should operate on a copy of the listener list, unaffected by adding or removing listeners during the process of notification.  And ideally, notification should also be independent of (make no guarantee about) order of notification.

**Comment by jessegreenberg** [comment]
> Notification should operate on a copy of the listener list, unaffected by adding or removing listeners during the process of notification.

What is the reason for this?

**Comment by pixelzoom** [comment]
Iterating over a list while it is potentially being modified is generally problematic. Let me know if you'd like a concrete example.   Beyond that general problem (which is not unique to Observer)...

Allowing the observer list to be modified during notification can result in subtle/difficult bugs that are rooted in order dependencies.  For example, change the order of registering and you may change the order that something is added/removed. If you can avoid doing so, it's best not to rely on the order that observers are added or removed, or the order that the observer list is traversed. 

Some APIs are explicit about this topic, some aren't. For example, [Java's Observable](https://docs.oracle.com/javase/7/docs/api/java/util/Observable.html) explicitly states that all observers will be notified:
> After an observable instance changes, an application calling the Observable's notifyObservers method causes all of its observers to be notified of the change by a call to their update method.  

... and warns against relying on order of notification:
> The order in which notifications will be delivered is unspecified. The default implementation provided in the Observable class will notify Observers in the order in which they registered interest, but subclasses may change this order, use no guaranteed order, deliver notifications on separate threads, or may guarantee that their subclass follows this order, as they choose.

Finally, this might be good fodder to including in the description of `Observer` for https://github.com/phetsims/phet-info/issues/88.

**Comment by samreid** [comment]
> Iterating over a list while it is potentially being modified is generally problematic.

Can we change TinyEmitter so that adding or removing a listener during `emit` throws an error?

**Comment by jessegreenberg** [comment]
Thanks @pixelzoom, https://github.com/phetsims/axon/issues/249#issuecomment-505677756 helps a lot.

> Can we change TinyEmitter so that adding or removing a listener during emit throws an error?

I worry that would be too restrictive and we will find cases where it is beneficial to add/remove listeners during an emit call. For instance, disposing an Emitter during an emit seems very reasonable/useful to me.

**Comment by samreid** [comment]
Notes from dev meeting:

We outlined two potential problems with our Emitter algorithm:

* self reentrant (emitting while emitting)
    * JO: this isn't a logical error, there is no need to assert out here.
    * SR: what is the case here?
* error if add/remove while emitting
    * JO: this gives the most flexibility, not a bug
    * JO: We need a way to add/remove listeners at any point.
    * We need a way for a listener to be able to remove its self.


const e = new EMitter
e.addLIstener (()=>{ e.emit() }); // where does this work in practice wihtout a stack overflow on TinyEmitter.activeListenersStack?

1. layout container. If bounds change then emit a layout change which recalculates its bounds (second bounds calc won't change).
2. Bounds listeners for text reflow, if tech change size, then reflow, which rechanges bounds then changes size which changes bounds (won't rechange bounds).

Since we already decided that Property reentry is sometimes natural, and Property changes are powered by TinyEmitter, as a consequence Emitter must allow re-entry.

@jonathanolson also advocated that there are many natural cases where you should be able to re-enter on emit or add/remove listeners during traversal and those should not be errors.  We recommend to close this issue.  @pixelzoom and @jbphet were not present at this meeting, please reopen if there is more to discuss.

**Comment by pixelzoom** [comment]
Reopening.  

It's not clear to me from the notes in https://github.com/phetsims/axon/issues/249#issuecomment-506463435 what was decided about the original issue.   That is: At the time that emit is called, are we operating on a copy of the list, so that the listeners that are notified is known at the time of the emit call?  Or are we operating on the list itself, such that the listeners may change during the emit call? 

> @jonathanolson also advocated that there are many natural cases where you should be able to re-enter on emit or add/remove listeners during traversal and those should not be errors. 

I agree. But whether listeners can be added/removed during emit is somewhat independent of whether the add/remove will affect the emit call.

**Comment by jessegreenberg** [comment]
`emit` does currently use a copy of the listener list for the reasons outlined in this issue and we agreed that was correct during the meeting.

**Comment by jessegreenberg** [comment]
Re-closing, please reopen if there are more questions.

**Comment by samreid** [comment]
One more note in case others pass this way in the future, in https://github.com/phetsims/axon/issues/215 we discussed that the sim behavior should be independent of listener order.  Having a listener remove itself could satisfy that constraint, but having one listener remove another generally would not.
