### ISSUE TITLE
ObservableArray should be implemented with Emitter or TinyEmitter.

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#270]
Discovered while working on PhetioGroup, it seems ObservableArray predates emitter and duplicates a lot of its code.

**Comment by zepumph** [comment]
This is likely a prerequisite to https://github.com/phetsims/phet-io/issues/1661, so that we can add logic in Emitter (for general use) instead of just into Observable array. I'll take this on. 

My plan is to not change the API at all, but just change the implementation to use two emitters, in similar fashion to how `PhetioGroup` is set up.

**Comment by zepumph** [comment]
I also converted to es6 while I was in here, since I didn't see any usages of `ObservableArray.call`. Please review this conversion.

I have two specific questions:
- [ ] Should we keep the ObservableArray specific PhET-iO events? This isn't really the pattern we use anymore, as we are more emitter-centric.
- [ ] Related to the above but still independent, should we instrument the two arrays? Then we would get PhET-iO events when they were emitted. I think it is fine the way it is with the custom events, no strong preference from me.

**Comment by zepumph** [comment]
- [ ] Note, if we don't instrument the Emitters, then I think we should likely use TinyEmitter instead of Emitter.

**Comment by samreid** [comment]
It will simplify the implementation to instrument the Emitters and eliminate the custom events, and that sounds more maintainable to me.  I'm not sure how this would jive with https://github.com/phetsims/phet-io/issues/1661.  @zepumph how should we proceed?

**Comment by zepumph** [comment]
I think this is a step to do before https://github.com/phetsims/phet-io/issues/1661. Note though that that phet-io issue is not blocking any priorities or causing bugs.

**Comment by zepumph** [comment]
There is a good chance that AxonArray is the way of the future, and that ObservableArray will be deprecated. @samreid can you please comment on this issue in that context?

**Comment by samreid** [comment]
`createObservableArray` uses instrumented `Emitters`, closing.
