### ISSUE TITLE
Should NumberProperty.range optionally be a Property?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#274]
As part of https://github.com/phetsims/gravity-force-lab/issues/191 and  https://github.com/phetsims/projectile-motion/issues/192, @zepumph made NumberProperty.range optionally a Property.  @pixelzoom would you like to review this and determine whether there is a better strategy to use?

**Comment by pixelzoom** [comment]
I don't like overloading options in this manner, because the implementation then violates our naming convention for Properties - e.g. `this.range` might be a Property and should have name `this.rangeProperty` -- and that makes the code more difficult to grok and maintain.   But I can't think of a better way to address this.

I skimmed the changes, and I don't see anything amiss.   But I don't see any unit tests for this new functionality, so they should be added.

**Comment by samreid** [comment]
Thanks @pixelzoom, @zepumph can you please take a look at your convenience?

**Comment by zepumph** [comment]
What about two mutually exclusive options to NumberProperty, `range` and `rangeProperty`? That doesn't solve the access issue, `this.range` and `this.rangeProperty`.

I will add unit tests.

**Comment by zepumph** [comment]
Furthermore, https://github.com/phetsims/axon/commit/45582851a500981de9fe933cb3f00c5124281f9a should have been linked to its own issue in axon and given to someone for review. I apologize for this oversight.

**Comment by pixelzoom** [comment]
> What about two mutually exclusive options ...

I think I prefer the overriding to 2 options.

**Comment by zepumph** [comment]
What about making `this.range` and es5 getter that either gets the range, or gets the value of the range Property. So it always returns a `Range`. And then we add `this.rangeProperty {Property.<Range>|null}`  if the range provided is of type `Property`?

**Comment by pixelzoom** [comment]
I like this general direction a lot - option `range` can be `{Range|Property.<Range|null>}`, but the field is `{Property.<Range|null>} this.rangeProperty`.   If you want to add `get range()`, that would be fine as a convenience.  But it's unnecessary if `this.rangeProperty` is public (which I believe it should be).   And you'll need to treat `this.rangeProperty` like we do `enableProperty`.  The `NumberProperty` may or may not own it, so may or may not need to unlink from it.

**Comment by zepumph** [comment]
@pixelzoom, I agree with everything above except that I think thought the typedef was a bit strange. I thought that rangeProperty could be null, not that it could store a value of null. My thoughts are reflected in the above commit. Let me know if you disagree. I think that everything was straight forward and exactly as discussed except that I am just changing `this.range` whenever the Property changes, so I don't need to have an es5 getter. Like you said, it is better for `rangeProperty` to just be `@public (read-only)`.

Note that one of the tests I added is commented out, demonstrating one of the issues that you mentioned over in https://github.com/phetsims/axon/issues/277#issuecomment-573333881. We can take up more of the `setValueAndRange` specific stuff over there.

**Comment by pixelzoom** [comment]
I don't see any problem with`this.rangeProperty` being `{Property.<Range>|null}`. 

I really don't like having both `this.range` and `this.rangeProperty`.  I think having ES5 get/set for range is preferable, and more similar to what we've done in other PhET code.  If you disagree, solicit other opinions.

You're not using the proper pattern for cleaning up `this.rangeProperty` in `dispose`.  See the handling of `enabledProperty` in Checkbox.js.   Should be something like this:

```js
this.disposeNumberProperty = () => {
  if ( this.rangeProperty ) {
    if ( ownsRangeProperty ) {
      this.rangeProperty.dispose();
    }
    else {
      this.rangeProperty.unlink( rangePropertyObserver );
    }
  }
} ;
```

I didn't review the tests yet.

**Comment by samreid** [comment]
@pixelzoom said:

> A number of sims are failing CT for something related to SimTests, e.g.
arithmetic : phet-io-tests : assert
7 out of 8 tests passed. 1 failed.
SimTests: arithmetic: iframe api failed:
Uncaught Error: Assertion failed: unexpected Range: undefined
https://bayes.colorado.edu/continuous-testing/snapshot-1579658474411/phet-io-wrappers/js/tests/SimTests.js?bust=1579660703515:341

**Comment by samreid** [comment]
I started investigating this, but wasn't confident enough to push.  The main ideas are:

* Assign this.range properly at the beginning
* Validate based on this.range rather than options.range
* Rearrange assertions so it is clearer that they are run after initial state is ready

<details>
```diff
Index: js/NumberProperty.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/NumberProperty.js	(revision bb32594255f33a6dbb06af39bd593b3533fd76f8)
+++ js/NumberProperty.js	(date 1579697889427)
@@ -72,20 +72,14 @@
         options.numberType === 'Integer' && validate( value, VALID_INTEGER );
 
         // validate for range
-        if ( options.range ) {
-          const currentRange = this.range;
-          assert && assert( currentRange instanceof Range, `unexpected Range: ${currentRange}` );
-          validate( value, { isValidValue: v => currentRange.contains( v ) } );
+        if ( this.range ) {
+          validate( value, { isValidValue: v => this.range.contains( v ) } );
         }
       } );
-
-      // verify that validValues meet other NumberProperty-specific validation criteria
-      if ( options.validValues && this.assertNumberPropertyValidateValue ) {
-        options.validValues.forEach( this.assertNumberPropertyValidateValue );
-      }
 
       // @public {Range|null} (read-only) - if defined, provides the range of possible values (inclusive)
-      this.range = options.range;
+      // specified below
+      this.range = null;
 
       // @public (read-only) {Property.<Range>|null} - non null only if provided via options.range
       this.rangeProperty = null;
@@ -95,15 +89,24 @@
       if ( options.range instanceof Property ) {
         this.rangeProperty = options.range;
         rangePropertyObserver = range => {
+          assert && assert( range instanceof Range, `unexpected Range: ${range}` );
           this.range = range;
           this.assertNumberPropertyValidateValue && this.assertNumberPropertyValidateValue( this.value );
         };
         this.rangeProperty.link( rangePropertyObserver );
       }
+      else {
+        this.range = options.range;
+      }
 
       // validate initial value
       this.assertNumberPropertyValidateValue && this.assertNumberPropertyValidateValue( value );
 
+      // verify that validValues meet other NumberProperty-specific validation criteria
+      if ( options.validValues && this.assertNumberPropertyValidateValue ) {
+        options.validValues.forEach( this.assertNumberPropertyValidateValue );
+      }
+
       // @private
       this.disposeNumberProperty = () => {
         rangePropertyObserver && this.rangeProperty.unlink( rangePropertyObserver );
```
</details>

@zepumph can you please take a look, or we can chat about it at our PhET-iO meeting today?

**Comment by zepumph** [comment]
CT error was caused by phet-io tests clashing with the current approach we had for serializing and deserializing NumberPropertyIO state. 

The PhET-iO team took a new approach to handling range, and made an instrumented rangeProperty for every NumberProperty. This simplified a lot of code. Here is a summary of changes:

* We addressed @pixelzoom's requests from https://github.com/phetsims/axon/issues/274#issuecomment-576978144
* Support for creating our own rangeProperty, or using the one passed in
* Moving validation from "setting" time to "listener" time (to support deferred Properties).
* Created es5 getter and setter convenience functions. The getter was important to make sure that all usages of NumberProperty.range didn't break.
* wrapped range validation around `isDeferred` checks to support PhET-iO state setting bugs, and to better support `setValueAndRange` as an atomic opperation.
* added unit tests.

@pixelzoom please review.

**Comment by chrisklus** [comment]
@pixelzoom how do you feel about now adding RangeProperty to #221? The number of reported instances in https://github.com/phetsims/axon/issues/221#issuecomment-466432708 will greatly increase to be more on the order of the number of NumberProperty instances.

**Comment by pixelzoom** [comment]
Adding `RangeProperty` sounds OK to me.

**Comment by zepumph** [comment]
@pixelzoom please take a look at https://github.com/phetsims/axon/issues/274#issuecomment-577369798 also.

**Comment by KatieWoe** [comment]
CT issues appearing that look like:
```
equality-explorer-two-variables : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: value failed phetioType validator: undefined
Error: Assertion failed: value failed phetioType validator: undefined
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/assert/js/assert.js?bust=1579767303296:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/ValidatorDef.js?bust=1579767303377:308:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/validate.js?bust=1579767303377:30:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/Property.js?bust=1579767303377:141:34)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/Property.js?bust=1579767303377:144:14)
    at new NumberProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/NumberProperty.js?bust=1579767303377:96:30)
    at new Variable (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/equality-explorer/js/common/model/Variable.js?bust=1579767303377:40:26)
    at new TwoVariablesScene (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/equality-explorer-two-variables/js/twovariables/model/TwoVariablesScene.js?bust=1579767303377:29:23)
    at new TwoVariablesModel (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/equality-explorer-two-variables/js/twovariables/model/TwoVariablesModel.js?bust=1579767303377:21:41)
    at TwoVariablesScreen.createModel (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/equality-explorer-two-variables/js/twovariables/TwoVariablesScreen.js?bust=1579767303377:33:27)
id: Bayes Chrome
Approximately 1/22/2020, 11:26:19 PM
equality-explorer-two-variables : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: value failed phetioType validator: undefined
Error: Assertion failed: value failed phetioType validator: undefined
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/assert/js/assert.js?bust=1579767303296:22:13)
    at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/ValidatorDef.js?bust=1579767303377:308:41)
    at validate (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/validate.js?bust=1579767303377:30:20)
    at Property.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/Property.js?bust=1579767303377:141:34)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/Property.js?bust=1579767303377:144:14)
    at new NumberProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/axon/js/NumberProperty.js?bust=1579767303377:96:30)
    at new Variable (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/equality-explorer/js/common/model/Variable.js?bust=1579767303377:40:26)
    at new TwoVariablesScene (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/equality-explorer-two-variables/js/twovariables/model/TwoVariablesScene.js?bust=1579767303377:29:23)
    at new TwoVariablesModel (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/equality-explorer-two-variables/js/twovariables/model/TwoVariablesModel.js?bust=1579767303377:21:41)
    at TwoVariablesScreen.createModel (https://bayes.colorado.edu/continuous-testing/snapshot-1579760779003/equality-explorer-two-variables/js/twovariables/TwoVariablesScreen.js?bust=1579767303377:33:27)
id: Bayes Chrome
Approximately 1/22/2020, 11:26:19 PM
```
@samreid suggested it was related to this issue.

**Comment by pixelzoom** [comment]
Please assign back to me for review when CT is fixed.

**Comment by samreid** [comment]
I made an improvement that should fix some of the CT problems, not sure if there are more.

**Comment by samreid** [comment]
The related CT failures from this morning are resolved in my working copy.  Please reassign me or @zepumph if you see other trouble.

**Comment by zepumph** [comment]
I do not agree with https://github.com/phetsims/axon/commit/d4b681297503cd91bb83ef1cdc78f162e48fa881

the error was caused because of a buggy options being passed, and I don't think options.range should support `undefined`.

In my opinion for this issue:
* @samreid I would revert that undefined conversion
* Then assign @pixelzoom for review

**Comment by samreid** [comment]
Thanks! I'll take a look.

**Comment by samreid** [comment]
I reverted the undefined conversion, @zepumph can you please double check everything before sending to @pixelzoom

**Comment by zepumph** [comment]
Yes excellent thanks. Over to you @pixelzoom.

**Comment by zepumph** [comment]
Fixed unit tests when `?ea` not provided above.

**Comment by chrisklus** [comment]
There was significant pushback from designers today regarding NumberProperty always having an instrumented RangeProperty. The main reason was that there's added clutter throughout Studio under all of the `opacityProperty`s. They like that `opacityProperty`, `pickableProperty`, and `visibleProperty` had a uniform structure as leaves for every Node, but now `opacityProperty` has a child. This also allows for the three Properties to not be grouped together for a node, see below:

![image](https://user-images.githubusercontent.com/5618316/73032560-72d0b980-3e0d-11ea-9f25-fa7c1b8efba2.png)

So, I know we like this change to NumberProperty. Any thoughts for how we can get the best of both worlds? Is making the RangeProperty instrumentation opt-in a possibility? It seems like that could allow for some weird states.

**Comment by zepumph** [comment]
That would be fine with me. We already have `rangePropertyOptions`, so if you want to instrument the rangeProperty then you can just pass in a tandem that way. I'll implement.

**Comment by pixelzoom** [comment]
It sounds like this is still in progress, so I'm self-unassigning.  Assign back to me when it's ready for review.

**Comment by zepumph** [comment]
Yes thanks @pixelzoom for your patience while we work out design and dev kinks here. In the above commits I optionally instrumented rangeProperty, and added an assertion to make sure that if instrumented, the tandem is "rangeProperty" for the default `rangeProperty`. Currently there are no instrumented rangeProperties, but we can add more as we see fit and design more phet-io instrumented sims. The noise and clutter that the design team mentioned in https://github.com/phetsims/axon/issues/274#issuecomment-577928765 is reasonable to me. There were >700 non-opacityProperty instrumented rangeProperties and many more opacityProperty rangeProperties throughout the project. I think it is best to opt into it, especially since every one of them currently is not changing for the lifetime of the Property (since mutable ranges was just added).

I like this better as an opt-in as opposed to an opt out for `NodeIO.opacityProperty`.

From this I think we are ready for a review @pixelzoom (he said with fingers in the crossed position).

**Comment by zepumph** [comment]
I just found another two bugs and added some tests. I am getting more and more confident about our cleanup by the minute!

Allow me to summarize the changes in this issue as they pertain to a review from @pixelzoom:
* `options.range` supports `{Range|null|Property.<Range|null>}`
* If options.range is not a `Property` (`null` or `Range`), then NumberProperty creates its own `rangeProperty`.
* a NumberProperty's range is now mutable via its `rangeProperty`.
* `rangeProperty` is a public member `{Property.<Range|null>}`, and can be optionally instrumented for PhET-iO via `rangePropertyOptions`.
* `NumberPropertyIO` still serializes range as part of its state (see NumberPropertyIO.toStateObject), this is to support studio code, and for clarity since rangeProperty isn't always instrumented. NumberPropertyIO does no deserializing of the range (i.e. it cannot set state on the rangeProperty of a numberProperty instance).
* `this.range` became es5 getter/setters for convenience. In this way we didn't have to change the api for accessing the current range of a NumberProperty
* we adapted `assertNumberPropertyValidateValue` to look at the "current" range instead of that passed from options. This was the main logic needed to make a NumberProperty range mutable (which it is now).
* validating with `assertNumberPropertyValidateValue` was moved from `set` to a listener. While this is a bit atypical, we found that it worked really nicely when deferring Properties to set the range and value at the same time.
* setValueAndRange was rewritten to use deferred Properties instead of mutation and private access the functions (this really belongs over in https://github.com/phetsims/axon/issues/277 but alas). This needed the previous bullet to work.
* Many unit tests were added to demonstrate these features.

Good luck!

**Comment by pixelzoom** [comment]
@zepumph and I collaborated on a bunch of changes in the above commit -- corrections and improvements. 

We'll leave this open until CT verifies.

**Comment by zepumph** [comment]
Looks like CT is clear! Closing
