### ISSUE TITLE
NumberProperty: should `validValues` and `range` options be mutually exclusive?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#284]
From #274, @samreid and I were wondering if this would be a good assertion to have. 

@pixelzoom can you think of a reason why both of these would want to be specified? Does using `assertMutuallyExclusiveOptions` here seem appropriate?

**Comment by pixelzoom** [comment]
I can't think of a use case where I'd use both `range` and `validValues`. And I also wonder about `range` and `isValidValue`.  

I guess I could invent cases like these, where I only want specific values in a range:

```js
new NumberProperty( ..., {
  range: new Range( 0, 25 ),
  validValues: [ 0, 5, 10, 15, 20, 25 ]
} );

new NumberProperty( ..., {
  range: new Range( 0, 100 ),
  isValidValue: value => ( value % 2 === 0 )
} );
```

But those seem odd, difficult for me to justify why a `range` is specified.  

The 1st example really seems bad, since I have to change both `validValues` and `range` if I want to change the set of valid values. Safer/cleaner to specify as:

```js
new NumberProperty( ..., {
  isValidValue: value => ( value >= 0 ) && ( value <= 25 ) && ( value % 5 === 0 )
} );
```

The 2nd case is a little less dubious; you can change `range` without having to touch `isValidValues`. But it's probably better to specify as:

```js
new NumberProperty( ..., {
  isValidValue: value => ( value >= 0 ) && ( value <= 100 ) && ( value % 2 === 0 )
} );
```

**Comment by zepumph** [comment]
I will add `assertMutuallyExclusiveOptions` to NumberProperty for `[ range ]` and `[ validValues, isValidValue ]`.
