### ISSUE TITLE
how to use NumberProperty with dynamic range?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#289]
Here's a real world problem that I'm having with NumberProperty in Natural Selection.   I've condensed it into this simplified example:

The model has a "generation clock" that advances in integer steps over time:

```js
class GenerationClock {
  constructor() {
    this.generationProperty = new NumberProperty( 0, {
      numberType: ‘Integer’
    } );
  }

  reset() {
    this.generationProperty.reset();
  }

  step( dt ) {
    // increment this.generationProperty as time advances
  }
}
```

The view has a spinner that selects which generation to display in the view.

```js
class GenerationSpinner extends NumberSpinner {

  // @param maxGenerationProperty - this is generationProperty from GenerationClock
  constructor( maxGenerationProperty ) {

    // range changes as the generation clock advances
    const selectedGenerationRangeProperty = new DerivedProperty( 
      [ maxGenerationProperty  ], maxGeneration => new Range( 0, maxGeneration ) 
    );

    // the generation that is selected by this spinner
    this.selectedGenerationProperty = new NumberProperty( 0, {
      numberType: ‘Integer’,
      range: selectedGenerationRangeProperty
    } );
  
    super( this.selectedGenerationProperty, selectedGenerationRangeProperty, {…} );
   }

  reset() {
    this.selectedGenerationProperty.reset();
  }
}
```

`selectedGenerationRangeProperty` must be defined first, because it's an option to `selectedGenerationProperty`.   Model is typically reset before view. When the model is reset, `selectedGenerationRangeProperty` gets reset first, to Range(0,0). If `selectedGenerationProperty` has been incremented even once (e.g. value=1), then `selectedGenerationProperty` will fail with "value failed isValidValue" because its value will now be out of the range.

I'm having difficulty finding an acceptable pattern for this case.  I suppose that I could reset the view before the model, so that `selectedGenerationProperty` gets reset before `selectedGenerationRangeProperty`.  But it's unusual to reset the view before the model, and it would presumably fail `?ea&shuffleListeners`.

@samreid @zepumph any ideas?  Asking because you've had the most involvement with NumberProperty.

**Comment by samreid** [comment]
Would `NumberProperty.setValueAndRange` help?

https://github.com/phetsims/axon/blob/ac530d0779c759ae4dd636965ca139fa42303bbe/js/NumberProperty.js#L183-L207

**Comment by pixelzoom** [comment]
> Would NumberProperty.setValueAndRange help?

Not in the case where the range is a DerivedProperty, because it can't be set directly.  I could resort to using a Property instead of a DerivedProperty for the range:

```js
const selectedGenerationRangeProperty = new Property( 0, {
  phetioType: PropertyIO( RangeIO ),
  phetioReadOnly: true
} );

maxGenerationProperty.link( maxGeneration => {
  const value = Math.min( selectedGenerationProperty.value, maxGeneration );
  const range = new Range( 0, maxGeneration );
  selectedGenerationProperty.setValueAndRange( value, range );
} );
```

But that seems like a workaround vs a solution.

The way I've solved this in Natural Selection (so far) is to move all of the Properties to the model, and make sure that `selectedGenerationProperty` is reset before `generationProperty`, with a comment describing the ordering dependency.

**Comment by pixelzoom** [comment]
Well, my "solution" in Natural Selection is causing other problems.  So back to the drawing board.

**Comment by pixelzoom** [comment]
> Would NumberProperty.setValueAndRange help?

NumberProperty has no corresponding `resetValueAndRange`, so I need to resort to something like this in `reset`:

```js
this. selectedGenerationProperty.setValueAndRange( 
  this.selectedGenerationProperty.initialValue,
  this.selectedGenerationRangeProperty.initialValue 
);
```

Should we add `resetValueAndRange` to NumberProperty?

**Comment by pixelzoom** [comment]
NumberProperty  `resetValueAndRange` has been added in https://github.com/phetsims/axon/issues/290.

**Comment by pixelzoom** [comment]
In the above commit, I resorted to the workaround described in https://github.com/phetsims/axon/issues/289#issuecomment-606985389.  The range is no longer a DerivedProperty, and I'm relying on `setValueAndRange` and `resetValueAndRange` to set `selectedGenerationProperty`.   I don't particularly like this, but I don't see another way to do this.

**Comment by pixelzoom** [comment]
Ugh. Now this is failing "Launch" in Studio.  When I press Reset All button in the launched sim, I get "Assertion failed: reentry detected".

**Comment by pixelzoom** [comment]
What I discovered is that if you instrument a NumberProperty, and use setValueAndRange, then you have better also instrument the associated range Property.  If you don't, then the range won't be saved/restored, and things will fail when you press Reset All in a launched sim.  And there is currently nothing in NumberProperty to verify this.

**Comment by samreid** [comment]
@zepumph has the most expertise on NumberProperty and setValueAndRange, so I'll self-unassign.  But invite me back if you wish.

**Comment by zepumph** [comment]
Thanks for working this out @pixelzoom, I see two side issues for this one:

https://github.com/phetsims/axon/issues/290
https://github.com/phetsims/axon/issues/291

Both of these are back in your court, and I hope that this workaround will effectively work. You should be able to revert https://github.com/phetsims/natural-selection/commit/e66d3a37716b7190522b6f17a9416180217739e7 now.

As for the use of the workaround, I agree that it is less than ideal. I was surprised how challenging the range/value setting ended up being when last working on NumberProperty. 

One thing that may help this situation is if we handle Property value validation (`Property.validate`) as a listener instead of embedded into `Property.prototype.set()`. We treat the NumberProperty validation as a listener, and perhaps that would simplify things as it pertains to the state engine (likely not the reset case though) because then both values can be deferred and thus their validation deferred until the range and value are both set correctly. 

I don't see this as a clear win though, I'm not too sure how to proceed. What do you think?

**Comment by pixelzoom** [comment]
I did not review code changes, but tested in natural-selection.  I removed instrumentation from `this.generationRangeProperty` in Proportions model, and verified in Studio/Launch/State Wrapper.  Behavior is as desired.

**Comment by zepumph** [comment]
In the above commit I ended up calling validate as a listener instead of built into `set`. This improves its support when deferred. I ended up going with this after @samreid and I ran into this same thing when  working on https://github.com/phetsims/axon/issues/276, and it ended up fixing a lot of stuff.

**Comment by pixelzoom** [comment]
Unit tests are failing in CT, looks like https://github.com/phetsims/axon/commit/8f597cf168dbe5fe6c58a4752d7048c3887b94cc may be the culprit.

**Comment by zepumph** [comment]
Tests fixed above. @pixelzoom thanks for the ping and sorry about the break.

**Comment by pixelzoom** [comment]
Validation change looks good. 

But I'm not clear...  Is the workaround that I described in https://github.com/phetsims/axon/issues/289#issuecomment-606995359 still necessary, or do I now have another choice?  `selectedGenerationRangeProperty` should be a DerivedProperty, but that still does not seem possible.

**Comment by zepumph** [comment]
Currently yes that is unfortunately the case. The reason is that we don't support the NumberProperty-specific code like `setValueAndRange` for DerivedProperty. I think much of it is to blame on our lack of multiple inheritance in that regard. 

I had another workaround-ish idea that I wanted to discuss to with you. What about in NaturalSelectionModel.reset(), resetting the proportionsModel before the environmental model. That way the dependency on the `rangeProperty` will reset after the `generationProperty`. Again this is finicky, but perhaps it is worth discussing. 

Also, I was unable to reproduce the problem with the above patch after the following:
* I applied it, 
* I went to the lab screen in studio
* I added a mate and waited for the next generation
* saw that the generationRangeProperty had been updated to [0,1]
* Reset and there was no bug. 

Perhaps the trick was to move the rangeProperty into the model?

Let me know what I'm not understanding, and if you would like to talk.

**Comment by pixelzoom** [comment]
Sorry to be so longer in getting back to this issue.  The above patch works great, thanks @zepumph! Closing.

**Comment by pixelzoom** [comment]
Reopening. Apparently there's still a problem, see https://github.com/phetsims/natural-selection/issues/78.

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/natural-selection/issues/78#issuecomment-629380597. 

Closing.

**Comment by pixelzoom** [comment]
Update: I ended up reverting the patch for generationRangeProperty, and resorting to making generationRangeProperty a Property instead of a DerivedProperty.  When I added this requirement:

```js
    // When the sim starts playing or the current generation changes, show the current generation immediately.
    Property.multilink(
      [ isPlayingProperty, currentGenerationProperty ],
...     
    );
```

... there was no way that I could make this work without using `generationProperty.setValueAndRange`.
