### ISSUE TITLE
TinyForwardingProperty should be able to forward to another TinyProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#337]
Currently we only have support for TinyForwardingProperty to forward to Property.  It seems to be more general and defensive, it should support being able to forward to TinyProperty as well.

One step will be to add `isPhetioInstrumented()` to TinyProperty, but we should be more thorough and add tests, etc to move forward on this.

**Comment by zepumph** [comment]
We seem to already support this, because there is a usage in master of passing one Node's visibleProperty to another Node as `visibleProperty`:

https://github.com/phetsims/wave-on-a-string/blob/120be3a51b535f00692a82867119c06dfac73076/js/wave-on-a-string/view/BottomControlPanel.js#L133-L132

I think we should add tests for this issue.

**Comment by zepumph** [comment]
See https://github.com/phetsims/scenery/issues/1046

**Comment by zepumph** [comment]
All that is left is tests.

**Comment by zepumph** [comment]
Looks all set to me. Closing
