### ISSUE TITLE
Property should use TinyProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#344]
I was quite surprised to discover in #343 that there is zero relationship between Property and TinyProperty.

TinyProperty doc describes it as "A lightweight version of Property (that satisfies some of the interface)". But Property currently uses a TinyEmitter, not a TinyProperty.  I don't understand the rationale for this.  If TinyProperty supports a subset of Property, why does Property not create an instance of TinyProperty and delegate everything it can to that instance?  Management of the value is the obvious responsibility that comes to mind, and I'm sure there are other responsibilities.

Also note that because there is no relationship between these classes, TinyProperty has been made to support "some of the interface" by wholesale copying of code from Property.  For example, take a look at `equalsValue` and `areValuesEqual`.  This level of duplication has no place in fundamental PhET classes.

So... I highly recommend backing Property with TinyProperty, delegating to it where possible. It will reduce duplication, and it will establish a coherent composition relationship between these classes.

Assigning to the PhET-iO team for starters, because TinyProperty seems to have emerged due to PhET-iO bloat in Property.

**Comment by pixelzoom** [comment]
Another example of the Property/TinyProperty problem.  I'm trying to create a Multilink in molecule-polarity. WebStorm is flagging it incorrect type assignment, see screenshot below.  And this is only working because Multilink isn't doing any type checking.

<img width="774" alt="screenshot_889" src="https://user-images.githubusercontent.com/3046552/110049887-f991de80-7d0f-11eb-914d-ecdc7a00b177.png">

**Comment by samreid** [comment]
I committed a proposed implementation.  Some methods could not forward to TinyProperty because we need to supply the Property as the `this` 3rd argument to link callbacks.

> Another example of the Property/TinyProperty problem. I'm trying to create a Multilink in molecule-polarity. WebStorm is flagging it incorrect type assignment, see screenshot below. 

Property will not be able to extend TinyProperty since it extends PhetioObject (we use composition instead), so I'm not sure how that problem can be addressed.

Ready for review, and this is a destabilizing change so I'l mark as blocks publication for now.

**Comment by samreid** [comment]
Self-reassigning to work on this part:

> For example, take a look at equalsValue and areValuesEqual

**Comment by samreid** [comment]
I also delegated `areValuesEqual`.  I could not find a good way to delegate `linkAttribute`.   Ready for review again.

**Comment by pixelzoom** [comment]
This issue has been labeled "blocks publication" and assigned to me to review.  I'm not available to review this until April 5 at the earliest.  If this blocks anything between now and then, please assign this to someone else for review.

**Comment by samreid** [comment]
At Thursday's dev meeting @jbphet said:

> I will likely try to redeploy Number Line: Integers from master next week

That seems like it will be before April 5, so I'll request review from @zepumph.

**Comment by zepumph** [comment]
Looks good in general. Thanks for doing this! I closed, which was on my list since TinyProperty was created.

>    if ( options.useDeepEquality ) {
      this.tinyProperty.useDeepEquality = options.useDeepEquality;
    }   

I think in Property.js it is fine to always assign this, even when falsey. No strong preference here.


>   * @protected
   */
  equalsValue( value ) {
    return this.areValuesEqual( value, this.get() );
  }
  
  
  Using `get()` (a function) is a performance hit as opposed to what it was (this._value), is this low-level enough that it matters in the project?

**Comment by samreid** [comment]
@zepumph and I reviewed the comments and opened a side issue.  This seems unblocked for publication.

**Comment by pixelzoom** [comment]
Looks good, closing.
