### ISSUE TITLE
Delete StringEnumerationProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#373]
From https://github.com/phetsims/chipper/issues/1106

**Comment by zepumph** [comment]
@samreid, does this feel right to you, once all usages have been changed?

**Comment by zepumph** [comment]
There are currently 9 usages of `new StringEnumerationProperty`. Presumably these will be refactored to use Enumeration.js

**Comment by samreid** [comment]
At today's design meeting, we agreed to eliminate `StringEnumerationProperty` and use `EnumerationValue` instead.

**Comment by zepumph** [comment]
There are still 9 usages of StringEnuemerationProperty. I'll add deprecated markings to it.

**Comment by samreid** [comment]
I'll be doing some of this work in https://github.com/phetsims/circuit-construction-kit-common/issues/827

**Comment by samreid** [comment]
Deleted, closing.

**Comment by samreid** [comment]
We have discussed that the string literal enumerations are nice and it would be good to have support for them.

**Comment by pixelzoom** [comment]
This is an odd way to vote for an “OR” choice.  Nothing preventing me from :+1::skin-tone-2: for both, so I’m going to do so.  Imo `StringUnionProperty` is a superior name, more idiomatic, and distances us from attempts to prohibit union types in favor of EnumerationValue.

**Comment by pixelzoom** [comment]
Changing my vote. I haven’t felt any need for QSM support of EnumerationValue.  Very slight :+1::skin-tone-2: for `StringUnionProperty`, if time permits.  I haven’t felt inconvenienced by this pattern, not sure if it’s worth the effort to remove 2 (?) lines of bolierplate:

```ts
    readonly raysTypeProperty: Property<MyStringUnion>;

    this.myStringUnionProperty = new Property( 'someValue', {
      validValues: MyStringUnionValues,
      tandem: options.tandem.createTandem( 'myStringUnionProperty' ),
      phetioType: Property.PropertyIO( StringIO )
    } );
```

**Comment by pixelzoom** [comment]
Some additional thoughts about supporting `EnumerationValue` in QSM...

The 'custom' type is already supported by QSM, and I use it regularly to support types like Range, RangeWidthValue, Color,... See GOQueryParameters.ts for examples of RangeWidthValue.  So it should be relatively easy to add support for a specific EnumerationValue.  And I wonder whether it's really necessay to add native support for EnumerationValue (if that was the intention).

Before doing anything related to EnumerationValue and QSM, there's a more fundamental problem: EnumerationValue and query parameters have incompatible string formats.  EnumerationValues are declared as static constants, with uppercase names like `DOT_PLOT` and `LINE_PLOT`. And EnumerationValue (too cleverly imo) converts those to uppercase strings `'DOT_PLOT'` and `'LINE_PLOT'`.  Those uppercase strings are unacceptable for use as query-parameter values, which uses lowerCamelCase.  (We had this discussuon in Geometric Optics with the `focalLengthControl` query parameter, which is one reason why I'm using a string union instead of Enumeration.)  So before putting effort into supporting EnumerationValue in QSM, you'll need to address this incompatibility.  (Automatically converting between uppercase and lowerCamelCase is imo not a path that should be taken.)

**Comment by pixelzoom** [comment]
When @samreid announced this poll in Slack, he said:
> context is https://github.com/phetsims/center-and-spread/blob/fa40acdfd780ea882baeeff82d3c9d6adeed9289/js/common/CASQueryParameters.ts

... which is:

```ts
  // TODO: It would be nice if QueryStringMachine supported mapping to EnumerationValue
  // TODO: Or should we bring back StringEnumerationProperty in https://github.com/phetsims/axon/issues/373?
  plotType: {
    type: 'string',
    validValues: [ 'dotPlot', 'linePlot' ],
    defaultValue: 'linePlot',
    public: true
  }
```

This looks like a nice place to use a string union.  I would change  to `validValue: PlotTypeValues`, and define the union like this:

```js
// PlotType.ts
export const PlotTypeValues = [ 'dotPlot', 'linePlot' ] as const;
export type PlotType = ( typeof PlotTypeValues )[number];
```

**Comment by samreid** [comment]
The results of the poll are:

@pixelzoom voted for `StringUnionProperty`, as described in https://github.com/phetsims/axon/issues/373#issuecomment-1059287885.  There were no other votes.

@chrisklus and I tried using the custom feature of Query String machine and it worked great, thanks!

**Comment by pixelzoom** [comment]
We're not deleting StringEnumertionProperty, and in fact have updated it for TypeScript. See https://github.com/phetsims/axon/issues/394.  Closing.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by samreid** [comment]
I moved the sim-specific TODO to a sim-specific issue, closing.
