### ISSUE TITLE
Multilink thinks second parameter can be null when it cannot

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#380]
I found a bug with the typing of Property.multilink. I'm unsure how to fix it, but it has a really easy reproducible case. By having the third Property which is of type `string|null`, the second arg in the callback thinks it could be null, but it can't. The assignment in the callback fails with this error:

```
TS2322: Type 'string | null' is not assignable to type 'string'.   Type 'null' is not assignable to type 'string'.
```

```ts

    const x = new Property<string>( 'hi' );
    const y = new Property<string>( 'hi' );
    const z = new Property<string | null>( 'hi' );
    Property.multilink( [ x, y, z ], ( xValue, yValue, zValue ) => {
      const foo: string = yValue;
    } );
```

**Comment by zepumph** [comment]
@jonathanolson, can you assist?

**Comment by zepumph** [comment]
I was able to easily workaround this by providing the parameters to multilink manuall (`<[string, string, string|null]>`), but likely we want this fixed generally since my workaround is a code smell when it could infer them.

**Comment by samreid** [comment]
This appears fixed in the latest implementation of multilink.  I added that test code and saw it seemed to be type checking OK.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/679486/176347338-f849eb92-e5b4-4f33-b89b-c3000002c498.png">

@zepumph can this issue be closed?
