### ISSUE TITLE
Property<true> is not assignable to type Property<boolean>

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#381]
This seems wrong.

```js
class Foo {

  readonly isActiveProperty: Property<boolean>;

  constructor() {

    // TS2322: Type 'Property<true>' is not assignable to type 'Property<boolean>'.
    this.isActiveProperty = new Property( true );
  }
}
```

**Comment by pixelzoom** [comment]
I guess TypeScript is inferring that Property(true) is a Property whose only possible value is true? So I would need to instantiate as:

```js
this.isActiveProperty = new Property<boolean>( true );
```

Do I understand that correctly?

**Comment by samreid** [comment]
There must be some other ingredient at play here, since just instantiating `new Property(true)` infers type `Property<boolean>`:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/679486/158678608-2b040bfe-2430-4fb6-a862-56a10ecd57ac.png">

But without understanding that nuance, yes, I think either `new Property<boolean>( true );` or `new BooleanProperty( true );` would be good.
