### ISSUE TITLE
questionable functions for poking a Property's stored and initial value

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#67]
axon.Property has these public functions:

```js
      // @public store the current (new) value
      storeValue: function( value ) {
        this._value = value;
      },

      // @public store the initial value
      storeInitialValue: function( value ) {
        this._initialValue = value;
      },
```

Both of these look dubious. Setting the value without notification, and changing the initial value. These are used in a handful of sims: fluid-pressure-and-flow, pendulum-lab, seasons, under-pressure. I'm especially leary of this in non-PhET code.

In the case of storeValue... It looks like this is used for setting a value without triggering notification. That seems like a generally bad idea, probably a workaround that involves another workaround to force a notification later.

In the case of storeInitialValue... Most (all?) look like lazy workarounds, where it would be better to design things so that the Property could be initialized with the proper value.  

Or perhaps I'm missing something... Assigning to @samreid  to comment on the use case where these are necessary, since it looks like he's the main user (other than MLL).

**Comment by samreid** [comment]
The only occurrence of storeValue outside of axon is in Pendulum Lab's Movable.js.  I'll delete it from axon and create an issue in Pendulum Lab to find another solution to the problem.

**Comment by samreid** [comment]
OK Property.storeValue is gone.  Next I'll look into storeInitialValue.

**Comment by samreid** [comment]
It looks like ObservableVector2, ObservableMatrix3, etc. are making good usage of storeInitialValue.  See https://github.com/phetsims/axon/issues/64 for some discussion about what ObservableVector2 etc are doing.  So perhaps we should change storeInitialValue to protected (use in subclasses OK but usage to work around buggy initial value not OK).  @pixelzoom what do you think of that plan?

**Comment by samreid** [comment]
On second thought, I think the subclass usages of storeInitialValue can/should probably move to the constructor.  I'll take a closer look before @pixelzoom's attention is needed.

**Comment by samreid** [comment]
> Most (all?) look like lazy workarounds, where it would be better to design things so that the Property could be initialized with the proper value.

The issue comes from our MVC initialization pattern: (1) create the model.  (2) create the view.  If the location of an item in the view depends on layout constraints, then the original model position may be incorrect.  That is where I see this pattern being used.  However, there are better ways to solve this--one way would be to move the model property out of the model (maybe it should have been a view property in the first place if it is sensitive to layout constraints). Another way to solve this is to relayout the view *after* the model has been reset.  In any case, I agree storeInitialValue seems like an abuse and I'm working on removing it.  Here is a summary of my changes:

not used:
dot/ObservableMatrix3.js
dot/ObservableBounds2.js

used only in John Travoltage where initial electron coordinates are irrelevant.
dot/ObservableVector2.js

fluid pressure and flow:
Used to position model elements in the control panels. When we revisit this sim, I suspect it may get floating layouts and hence this code will not work at all.

under pressure and pendulum-lab
I've converted the barometers to just update their position after reset, without using setInitialValue, and tested that they behave properly

seasons:
this sim is on hold and I have simply removed the offending code.

Will commit shortly.

**Comment by samreid** [comment]
@pixelzoom I'm ready for your feedback here, at your convenience.

**Comment by samreid** [comment]
The parts that would be good to review/discuss are:

* Look at the change sets: https://github.com/phetsims/axon/commit/1591786f5c5aef0c57bf5a3efa905dc1f2c9f4e0 and https://github.com/phetsims/axon/commit/537bd373fd52940b12da20d60369af9b88c8e93c and think about whether they will have unintended consequences

* what do you think about sims that create the model at some coordinates, then create the view item (with position based on mvt(model)), then adjusts the position of the view item, then the user presses reset.  How to handle getting it to go back to the correct view position, and not the original model location?

**Comment by pixelzoom** [comment]
> Look at the change sets: 1591786 and 537bd37 and think about whether they will have unintended consequences

I have no idea if removing storeValue and storeInitialValue will unintended consequences. I've never used them. And it looks like you've removed all call sites, so any consequences will probably be identifiable during testing.

> what do you think about sims that create the model at some coordinates, then create the view item (with position based on mvt(model)), then adjusts the position of the view item, then the user presses reset. How to handle getting it to go back to the correct view position, and not the original model location?

Sounds like a sim design problem to me.  Assuming that the location (coordinates) need to be in the model, then I don't see why the model shouldn't be initialized to the proper default value when it's instantiated.  And if the location is view-specific, then it shouldn't be in the model to begin with.

**Comment by samreid** [comment]
@pixelzoom and I discussed the latter point.  One suggestion was to have switchable coordinates for the model tools and a property to indicate which coordinate frame the tool is in.  We are good to close this issue though.
